<?php
/**
 * Helper function that returns an empty variant ready to be set up
 */
function _artesis_frontend_variants_create_variant($term = NULL) {
  if (is_null($term)) {
    return FALSE;
  }

  // Generate some unique names and other needed info
  $handler_name = 'term_view_term_id_' . $term->tid;
  $variant_title = 'Variant for ' . $term->name;
  $access_plugin_settings = array(
    'vid' => $term->vid,
    $term->vid => array(
      $term->tid => $term->tid,
    ),
  );
  $left_panel_pane = 'new-l-' . $term->tid;
  $right_panel_pane = 'new-r-' . $term->tid;
  $pipeline = module_exists('panels_ipe') ? 'ipe' : 'standard';

  // Create a new variant based on an existing term
  $handler = new stdClass;
  $handler->disabled = FALSE; /* Edit this to true to make a default handler disabled initially */
  $handler->api_version = 1;
  $handler->name = $handler_name;
  $handler->task = 'term_view';
  $handler->subtask = '';
  $handler->handler = 'panel_context';
  $handler->weight = -50;
  $handler->conf = array(
    'title' => $variant_title,
    'no_blocks' => 0,
    'pipeline' => $pipeline,
    'body_classes_to_remove' => '',
    'body_classes_to_add' => '',
    'css_id' => '',
    'css' => '',
    'contexts' => array(),
    'relationships' => array(
      0 => array(
        'identifier' => 'Taxonomy vocabulary from Taxonomy term (on taxonomy_term_data.vocabulary)',
        'keyword' => 'taxonomy_vocabulary',
        'name' => 'entity_from_schema:vid-taxonomy_term-taxonomy_vocabulary',
        'context' => 'argument_term_1',
        'id' => 1,
      ),
    ),
    'access' => array(
      'plugins' => array(
        0 => array(
          'name' => 'term',
          'settings' => $access_plugin_settings,
          'context' => 'argument_term_1',
          'not' => FALSE,
        ),
      ),
      'logic' => 'and',
    ),
  );
  $display = new panels_display;
  $display->layout = 'omega_12_mainpage_complex';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'top_left' => NULL,
      'top_right' => NULL,
      'middle' => NULL,
      'bottom_left_small' => NULL,
      'bottom_right_small' => NULL,
      'bottom_medium_right' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = '%term:parent';
  $display->content = array();
  $display->panels = array();

  // Left panel pane - Menu
  $pane = new stdClass;
  $pane->pid = $left_panel_pane;
  $pane->panel = 'top_left';
  $pane->type = 'views';
  $pane->subtype = 'parent_vocabulary_terms';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_pager_settings' => 0,
    'use_pager' => 0,
    'nodes_per_page' => '0',
    'pager_id' => '0',
    'offset' => '0',
    'more_link' => 0,
    'feed_icons' => 0,
    'panel_args' => 0,
    'link_to_view' => 0,
    'args' => '',
    'url' => '',
    'display' => 'block_1',
    'context' => array(
      0 => 'relationship_entity_from_schema:vid-taxonomy_term-taxonomy_vocabulary_1.vid',
      1 => '',
    ),
    'override_title' => 1,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $display->content[$left_panel_pane] = $pane;
  $display->panels['top_left'][0] = $left_panel_pane;

  // Right panel pane - Content
  $pane = new stdClass;
  $pane->pid = $right_panel_pane;
  $pane->panel = 'top_right';
  $pane->type = 'views';
  $pane->subtype = 'taxonomy_term';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_pager_settings' => 0,
    'use_pager' => 1,
    'nodes_per_page' => '0',
    'pager_id' => '0',
    'offset' => '0',
    'more_link' => 0,
    'feed_icons' => 0,
    'panel_args' => 1,
    'link_to_view' => 0,
    'args' => '1',
    'url' => '',
    'display' => 'page',
    'context' => array(
      0 => 'argument_term_1.tid',
      1 => '',
    ),
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $display->content[$right_panel_pane] = $pane;
  $display->panels['top_right'][0] = $right_panel_pane;
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = $right_panel_pane;
  $handler->conf['display'] = $display;

  // Save the handler
  page_manager_save_task_handler($handler);
  return TRUE;
}

/**
 * Implements hook_taxonomy_term_insert().
 */
function artesis_frontend_variants_taxonomy_term_insert($term) {
  $voc = taxonomy_vocabulary_machine_name_load('eddb_editorial_base');
  // Fire logic only for editorial base vocabulary.
  if ($voc && $voc->vid == $term->vid) {
    // Add a menu link
    $link = array();
    $link['link_path'] = 'taxonomy/term/' . $term->tid;
    $link['link_title'] = $term->name;
    $link['menu_name'] = 'main-menu';
    $link['weight'] = $term->weight;

    $parent = array_pop($term->parent);
    if ($parent) {
      $parent_term = taxonomy_term_load($parent);
      $plid = artesis_frontend_variants_get_menu_item_mlid($parent_term->name, 'main-menu');

      if ($plid) {
        $link['plid'] = $plid;
      }
    }

    menu_link_save($link);
    menu_cache_clear_all();

    // Add a new variant for the given term.
    ctools_include('plugins');
    $handler = _artesis_frontend_variants_create_variant($term);
    if ($handler) {
      drupal_set_message(t('Variant created for term \'!term\'.', array('!term' => $term->name)));
    }
  }
}

/**
 * Implements hook_taxonomy_term_delete().
 *
 * Since the taxonomy and the menus can be renamed without affecting each other,
 * this will delete only the menus matching the taxonomy term by name.
 */
function artesis_frontend_variants_taxonomy_term_delete($term) {
  $voc = taxonomy_vocabulary_machine_name_load('eddb_editorial_base');
  // Fire logic only for editorial base vocabulary.
  if ($voc->vid == $term->vid) {
    $mlid = artesis_frontend_variants_get_menu_item_mlid($term->name, 'main-menu');

    // Delete menu item
    if ($mlid) {
      menu_link_delete($mlid);
    }

    // Delete variant
    $handler_name = 'term_view_term_id_' . $term->tid;
    $handler = new stdClass;
    $handler->name = $handler_name;
    $handler->handler = 'panel_context';
    ctools_include('plugins');
    page_manager_delete_task_handler($handler);
    drupal_set_message(t('Variant for term \'!term\' deleted.', array('!term' => $term->name)));

  }
}

/**
 * Get menu item id by it's name.
 *
 * @param $name
 *   Menu name to seek.
 * @return
 *   Menu id (mlid), or 0.
 */
function artesis_frontend_variants_get_menu_item_mlid($name, $menu = 'main-menu') {
  $menu_links = menu_load_links($menu);

  foreach ($menu_links as $link) {
    if ($link['link_title'] == $name) {
      return $link['mlid'];
    }
  }

  return 0;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function artesis_frontend_variants_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_taxonomy_term_update().
 * Update menu link item when modifying term.
 */
function artesis_frontend_variants_taxonomy_term_update($term) {
  // Check if the term belongs to 'Section' vocabulary.
  $voc = taxonomy_vocabulary_machine_name_load('eddb_editorial_base');
  if (!empty($voc) && $voc->vid != $term->vid) {
    return;
  }
  unset($voc);

  // Get menu link by term path
  $link = menu_link_get_preferred($term->path['source']);

  if ($link) {
    // Modify menu link
    $link['link_title'] = $term->name;
    $link['weight'] = $term->weight;

    // Update parent
    $parent = array_pop($term->parent);
    if ($parent) {
      $parent_term = taxonomy_term_load($parent);
      $plid = artesis_frontend_variants_get_menu_item_mlid($parent_term->name, 'main-menu');
      unset($parent_term);

      if ($plid) {
        $link['plid'] = $plid;
      }
    }
    else {
      // Parent is root
      $link['plid'] = 0;

      // Update parents
      $link['p1'] = $link['mlid'];
      for ($i=2; $i<10; $i++) {
        $link['p' . $i] = 0;
      }

    }

    // Save modified menu link
    menu_link_save($link);

    // Clear menu cache
    menu_cache_clear_all();
    unset($link);
  }
  else {
    watchdog('artesis_frontend_variants',
      t('Menu link for :term was not found', array(':term' => $tern->name))
    );
  }
}

/**
 * Implementation of hook_form_alter()
 */
function artesis_frontend_variants_form_alter(&$form, &$form_state, $form_id) {
  // Apply only to 'Section' vocabulary
  if ($form_id == 'taxonomy_overview_terms' && $form['#vocabulary']->machine_name == 'eddb_editorial_base') {
    $form['#submit'][] = '_artesis_frontend_variants_reorder_menu';
  }
}

/**
 * Reorder menu items based on new term weights and parents
 */
function _artesis_frontend_variants_reorder_menu($form, &$form_state) {
  // Get term weights and parents.
  $terms = array();
  $tree = array();
  foreach ($form_state['values'] as $k => $v) {
    if (strpos($k, 'tid:') === 0) {
      $terms[$v['tid']] = array(
        'tid' => $v['tid'],
        'parent' => $v['parent'],
        'weight' => $v['weight'],
        'depth' => $v['depth'],
      );

      // Build partial tree.
      $tree[$v['parent']][] = $v['tid'];
    }
  }

  // Load menu items.
  $menu = menu_tree_all_data('main-menu');

  // Set new weight/parent for each item.
  $min_weight = -50;
  foreach ($menu as $v) {
    // Get minimal weight for term links in main menu.
    if ($v['link']['router_path'] != 'taxonomy/term/%') {
      $min_weight = $v['link']['weight'];
    }
  }
  unset($menu);

  // Rebuild menu items.
  foreach ($tree[0] as $tid) {
    _artesis_frontend_variants_reorder_menu_item($terms[$tid], $tree, $min_weight, $terms);
  }

  // All done, clear cache
  menu_cache_clear_all();
}

/**
 * Update menu item
 */
function _artesis_frontend_variants_reorder_menu_item($item, $tree, $min_weight = NULL, $terms) {
  $tid = $item['tid'];
  $link = menu_link_get_preferred('taxonomy/term/' . $tid, 'main-menu');

  if (empty($link)) {
    watchdog('artesis_frontend_variants',
      t('Menu link for :term was not found (reorder menu item)', array(':term' => $tid))
    );
    return;
  }

  // Set new weight
  $weight = $item['weight'];

  // For root elements set weight depending on $min_weight
  if ($item['depth'] == 1) {
    $weight += $min_weight + 1;
  }
  $link['weight'] = $weight;
  $link['depth'] = $item['depth'];

  // Set parents
  if ($item['parent'] == 0) {
    // Root item
    $link['p1'] = $link['mlid'];
    for ($i=2; $i<10; $i++) {
      $link['p' . $i] = 0;
    }
    $link['plid'] = 0;
  }
  else {
    // Get parent menu item
    $parent_link = menu_link_get_preferred('taxonomy/term/' . $item['parent'], 'main-menu');
    $link['plid'] = $parent_link['mlid'];

    // Copy parents from parent
    for ($i=1; $i<10; $i++) {
      $link['p' . $i] = $parent_link['p' . $i];
    }

    // Set current link to parent in proper depth
    $link['p' . $item['depth']] = $link['mlid'];
  }

  // Save changes
  menu_link_save($link);

  // Update child items
  if (!empty($tree[$tid])) {
    foreach ($tree[$tid] as $ctid) {
      _artesis_frontend_variants_reorder_menu_item($terms[$ctid], $tree, NULL, $terms);
    }
  }
}
